// components/common/AWeek.vue
<script setup lang="ts">
import type { Week } from 'types/Week';
import ADate from 'components/common/ADate.vue';

interface Props {
  week: Week;
}

const props = defineProps<Props>();

const displayMonth = (date: Date, index: number): boolean => {
  if (props.week.dates.length === 1) return true;
  if (index + 1 === props.week.dates.length) return true;
  if (props.week.dates[index + 1].getMonth() !== date.getMonth()) return true;
  return false;
};

const displayComa = (index: number): boolean => {
  if (displayMonth(props.week.dates[index], index)) return false;
  return props.week.dates.length > 1 && index < props.week.dates.length - 1;
};

const displayAnd = (index: number): boolean => {
  return displayMonth(props.week.dates[index], index) && index < props.week.dates.length - 1;
};
</script>

<template>
  <div>
    <p>
      Semaine {{ week.day }}
      <template v-for="(date, index) in week.dates" :key="index">
        <ADate :date="date" :display-month="displayMonth(date, index)" />
        <template v-if="displayComa(index)">-</template>
        <template v-else-if="displayAnd(index)">et</template>
      </template>
    </p>
  </div>
</template>

// src/components/AWeek.svelte
<script lang="ts">
	import type { Week } from '../types/Week';
	import ADate from './ADate.svelte';

	let { week }: { week: Week } = $props();
  
	const displayMonth = (date, index) => {
		if (week.dates.length === 1) return true;
		if (index + 1 === week.dates.length) return true;
		if (week.dates[index + 1].getMonth() !== date.getMonth()) return true;
		return false
	};

  const displayComa = (index) => {
    if (displayMonth(week.dates[index], index))
      return false;
    return week.dates.length > 1 && index < week.dates.length - 1;
  }

  const displayAnd = (index) => {
    return displayMonth(week.dates[index], index) && index < week.dates.length - 1
  }
</script>

<div>
  <p>
    Semaine {week.day}
    {#each week.dates as date, index}
			<ADate {date} displayMonth={displayMonth(date, index)} />
			{#if displayComa(index)}
				-
      {:else if displayAnd(index)}
        et
			{/if}
		{/each}
	</p>
</div>
